[package]
name = "oxtail"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.20"
crossterm = "0.26"
chrono = "0.4"
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
serde_json = "1.0"
strip-ansi-escapes = "0.2.0"
regex = "1.9"
